name: $(TeamProject)_$(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)
trigger:
  branches:
    include:
    - release/*
    - feature/*
    - bugfix/*
    - hotfix/*
  paths:
    include:
    - db/*
    exclude:
    - pipeline/*

stages:
- template: authorize_db_stage_template.yml
  parameters:
    target: dev
    buildConfiguration: 'Release'
    buildPlatform: 'Any CPU'

- template: authorize_db_stage_template.yml
  parameters:
    target: test
    buildConfiguration: 'Release'
    buildPlatform: 'Any CPU'

- template: authorize_db_stage_template.yml
  parameters:
    target: prod
    buildConfiguration: 'Release'
    buildPlatform: 'Any CPU'